POST http://localhost:3000/set HTTP/1.1
Content-Type: application/json

{
    "Title":"hello world",
    "Author":"Jara",
    "Language":"Dutch (Belgium)",
    "Words":[
        {
            "value":"Water",
            "Correct":2,
            "Mistake":0
        },
        {
            "value":"Cola",
            "Correct":0,
            "Mistake":2
        },
        {
            "value":"Ice Tea",
            "Correct":1,
            "Mistake":1
        },
        {
            "value":"Sprite",
            "Correct":0,
            "Mistake":0
        },
        {
            "value":"Cola-Zero",
            "Correct":0,
            "Mistake":3
        },
        {
            "value":"Nestea",
            "Correct":2,
            "Mistake":0
        },
        {
            "value":"Tonisteiner",
            "Correct":3,
            "Mistake":2
        }
    ]
}

###

GET http://localhost:3000/set HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6IlZlcmJydWdnaGUgSmFyYSIsImNpdHkiOiJUaWVsdCIsIm5iZiI6MTY1MDk5OTg0MiwiZXhwIjoxNjUyNzk5ODQyLCJpc3MiOiJodHRwczovLzAuMC4wLjA6MzAwMCIsImF1ZCI6InNwZWxsaXRfYXBpX3VzZXJzIn0.4AyUTcEQ4VI9wERgdQ4YUjWera5dY-ejSyW-Ipgw4o8

###

GET http://localhost:3000/folder HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/folder HTTP/1.1
Content-Type: application/json

{
    "Title":"folderenglsih",
    "Author":"rubiks",
    "set":[]
    
    
}

###

POST http://localhost:3000/authentication HTTP/1.1
Content-Type: application/json

{
    "username":"jarav",
    "password":"secret"
}
